language: java

sudo: required

cache:
  directories:
    - $HOME/.m2/repository

services:
  - docker

script: true
install: true

stages:
  - build
  - test
  - integration-test
  - acceptance-test

jobs:
  include:
    - stage: build
      script:
        - mvn clean test-compile --settings "settings.xml"
    - stage: test
      script:
        - mvn test jacoco:report coveralls:report --settings "settings.xml"
    - stage: integration-test
      script:
        - docker run -dit --name emscripten -v $(pwd):/src trzeci/emscripten:sdk-incoming-64bit bash
        - ./install_armadillo.sh
        - mvn verify -P integration-test jacoco:report coveralls:report --settings "settings.xml"
    - stage: acceptance-test
      script:
        - true
        #- mvn verify -P acceptance-test jacoco:report coveralls:report --settings "settings.xml"

after_success:
#- mvn deploy --settings "./settings.xml"
