language: java

cache:
  directories:
    - $HOME/.m2/repository

script: true
install: true

stages:
  - acceptance-test

jobs:
  include:
    - stage: acceptance-test
      sudo: required
      services:
        - docker
      script:
        - mvn verify -Pacceptance-test --settings "settings.xml"

