language: java

sudo: required

services:
  - docker

before_install:
  - ./install_emscripten.sh
  - ./install_armadillo.sh
  - ./test_env/test_compile.sh

script:
#- mvn clean install jacoco:report org.eluder.coveralls:coveralls-maven-plugin:report --settings "settings.xml"

after_success:
#- mvn deploy --debug --settings "./settings.xml"
